lib/phoenix1_web/router.ex
defmodule Phoenix1Web.Router do
  use Phoenix1Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Phoenix1Web.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phoenix1Web.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Phoenix1Web do
    pipe_through :browser

    get "/", PageController, :index
    get "/hello", HelloController, :index
    get "/show", HelloController, :show
    # resources "/users", UserController, only: [:index, :show] resource routes
  end

  # Other scopes may use custom stacks.
  # scope "/api", Phoenix1Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: Phoenix1Web.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/phoenix1/application.ex
defmodule Phoenix1.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Phoenix1.Repo,
      # Start the Telemetry supervisor
      Phoenix1Web.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Phoenix1.PubSub},
      # Start the Endpoint (http/https)
      Phoenix1Web.Endpoint
      # Start a worker by calling: Phoenix1.Worker.start_link(arg)
      # {Phoenix1.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Phoenix1.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    Phoenix1Web.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/phoenix1/mailer.ex
defmodule Phoenix1.Mailer do
  use Swoosh.Mailer, otp_app: :phoenix1
end

lib/phoenix1/repo.ex
defmodule Phoenix1.Repo do
  use Ecto.Repo,
    otp_app: :phoenix1,
    adapter: Ecto.Adapters.Postgres
end

lib/phoenix1_web/controllers/hello_controller.ex
defmodule Phoenix1Web.HelloController do
  use Phoenix1Web, :controller

  @fake_ids [3,6,7]

  plug Phoenix1Web.Plugs.Locale, "fr" when action in [:show]

  plug :cast_parameters when action in [:show]
  plug :authenticate when action in [:show]

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def show(conn, %{"message" => message}) do
    render(conn, "show.html", message: message)
  end

  def show(conn, _params) do
    render(conn, "show.html", message: "not message")
  end

  defp cast_parameters(conn, _) do

    casted_params = conn.params
    |> Map.put(
      "user_id",
      conn.params["user_id"] && String.to_integer(conn.params["user_id"])
    )

    %{conn | params: casted_params}
  end

  # second argument is parameter passed to plug
  defp authenticate(conn, _) do
    params = conn.params

    ( params["user_id"] in @fake_ids &&
      assign(conn, :user_name, "Anderson")
    ) || halt(conn)

   end
end

lib/phoenix1_web/controllers/page_controller.ex
defmodule Phoenix1Web.PageController do
  use Phoenix1Web, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/phoenix1_web/views/error_view.ex
defmodule Phoenix1Web.ErrorView do
  use Phoenix1Web, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/phoenix1_web/views/hello_view.ex
defmodule Phoenix1Web.HelloView do
  use Phoenix1Web, :view
end

lib/phoenix1_web/views/layout_view.ex
defmodule Phoenix1Web.LayoutView do
  use Phoenix1Web, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/phoenix1_web/views/page_view.ex
defmodule Phoenix1Web.PageView do
  use Phoenix1Web, :view
end

lib/phoenix1_web/templates/hello/index.html.heex
<section class="phx-hero">
    <h2>Hello world!</h2>
</section>

lib/phoenix1_web/templates/hello/show.html.heex
<section class="phx-hero">
    <h2>
       <%= @message %>
    </h2>
</section>

lib/phoenix1_web/templates/layout/app.html.heex
<main class="container">
  <%= link "link", to: Routes.hello_path(@conn, :show, user_id: 3)%>
  <p>Locale: <%= @locale %></p>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/phoenix1_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/phoenix1_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Phoenix1", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/phoenix1_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>